services:
  api:
    build: .
    ports:
      - "3000"
    environment:
      - NODE_ENV=production
      - IMGPROXY_URL=http://imgproxy:8080
      - SUPABASE_PUBLIC_STORAGE_BASE=${SUPABASE_PUBLIC_STORAGE_BASE}
      - MAX_IMAGE_WIDTH=${MAX_IMAGE_WIDTH:-2048}
      - MAX_IMAGE_HEIGHT=${MAX_IMAGE_HEIGHT:-2048}
    healthcheck:
      test: "wget -qO- http://localhost:3000/health || exit 1"
      interval: 2s
      timeout: 10s
      retries: 5
    depends_on:
      imgproxy:
        condition: service_healthy
  imgproxy:
    image: darthsim/imgproxy
    environment:
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_USE_ETAG=true
      - ALLOWED_REMOTE_DOMAINS=${ALLOWED_REMOTE_DOMAINS}
      - IMGPROXY_AUTO_WEBP=true
      - IMGPROXY_AUTO_AVIF=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
      - IMGPROXY_ENABLE_AVIF_DETECTION=true
      - IMGPROXY_PREFERRED_FORMATS=avif,webp,jpeg,png,gif
      - IMGPROXY_WORKERS=${IMGPROXY_WORKERS:-2}
      - IMGPROXY_ONLY_PRESETS=true
      - IMGPROXY_PRESETS=default=resizing_type:fit,w_320=w:320,w_480=w:480,w_640=w:640,w_720=w:720,w_960=w:960,w_1280=w:1280,w_1600=w:1600,w_2048=w:2048,h_320=h:320,h_480=h:480,h_640=h:640,h_720=h:720,h_960=h:960,h_1280=h:1280,h_1600=h:1600,h_2048=h:2048,q_50=q:50,q_75=q:75,q_85=q:85
      - IMGPROXY_MAX_RESULT_DIMENSION=${IMGPROXY_MAX_RESULT_DIMENSION:-2048}
      - IMGPROXY_ALLOWED_SOURCES=${IMGPROXY_ALLOWED_SOURCES:-https://${ALLOWED_REMOTE_DOMAINS}/}
      - IMGPROXY_MAX_SRC_RESOLUTION=${IMGPROXY_MAX_SRC_RESOLUTION:-50}
      - IMGPROXY_MAX_SRC_FILE_SIZE=${IMGPROXY_MAX_SRC_FILE_SIZE:-10485760}
      - IMGPROXY_MAX_ANIMATION_FRAMES=${IMGPROXY_MAX_ANIMATION_FRAMES:-1}
      - IMGPROXY_DOWNLOAD_TIMEOUT=${IMGPROXY_DOWNLOAD_TIMEOUT:-5}
      - IMGPROXY_READ_REQUEST_TIMEOUT=${IMGPROXY_READ_REQUEST_TIMEOUT:-10}
      - IMGPROXY_WRITE_RESPONSE_TIMEOUT=${IMGPROXY_WRITE_RESPONSE_TIMEOUT:-10}
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      interval: 2s
      timeout: 10s
      retries: 5
